export { default as Home } from './Home'
export { default as List } from './List'
export { default as Alerts } from './Alerts'
export { default as Profile } from './Profile'
export { default as Settings } from './Settings'